AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Dynamic references - Lambda memory size (uksb-1q9p31idr) (tag:dynamic-references).

Resources:
  FunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Path: /
  ## Lambda Resource Goes Here
  BetterFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt FunctionExecutionRole.Arn
      Handler: index.handler
      Runtime: python3.9
      MemorySize: "{{resolve:ssm:/lambdas-configurations/memorySize}}"
      Code:
        ZipFile: |
          # Version: 1.0.1
          import os
          def handler(event, context):
              LAMBDA_MEMORY_SIZE = os.getenv("LAMBDA_MEMORY_SIZE")
              return "lambda Memory Size: {}".format(LAMBDA_MEMORY_SIZE)
      Environment:
        Variables:
          LAMBDA_MEMORY_SIZE: "{{resolve:ssm:/lambdas-configurations/memorySize}}"
